Repository 3scale-sre/marin3r, pull requests merged in 2020-11, with the labels that each got.

#50 Increase memory request/limit of controller-manager
  config/manager/manager.yaml
Labels: bug

#49 Add desing doc on discovery service
  README.md
  docs/design/discovery-service.md
  docs/design/discovery-service.svg
Labels: documentation

#51 Add sidecar injection design doc
  README.md
  docs/design/operator.md
  docs/design/sidecar-injection.md
  docs/design/sidecar-injection.svg
Labels: documentation

#52 doc/design-operator
  README.md
  docs/design/operator.md
Labels: documentation

#48 Dual v2/v3 xds server
  controllers/envoy/envoyconfig_controller.go
  controllers/envoy/envoyconfig_controller_test.go
  controllers/envoy/envoyconfigrevision_controller.go
  controllers/envoy/envoyconfigrevision_controller_test.go
  controllers/envoy/revisions.go
  controllers/envoy/revisions_test.go
  controllers/envoy/rollback.go
  controllers/envoy/secret_controller_test.go
  controllers/envoy/secrets_controller.go
  controllers/operator/enabled_namespaces.go
  examples/e2e/pod/discoveryservice.yaml
  go.mod
  main.go
  pkg/discoveryservice/manager.go
  pkg/discoveryservice/xds_server.go
  pkg/discoveryservice/xds_server_test.go
  pkg/discoveryservice/xdss/interface.go
  pkg/discoveryservice/xdss/v2/cache.go
  pkg/discoveryservice/xdss/v2/cache_test.go
  pkg/discoveryservice/xdss/v2/callbacks.go
  pkg/discoveryservice/xdss/v2/callbacks_test.go
  pkg/discoveryservice/xdss/v2/snapshot.go
  pkg/discoveryservice/xdss/v2/snapshot_test.go
  pkg/discoveryservice/xdss/v3/cache.go
  pkg/discoveryservice/xdss/v3/cache_test.go
  pkg/discoveryservice/xdss/v3/callbacks.go
  pkg/discoveryservice/xdss/v3/callbacks_test.go
  pkg/discoveryservice/xdss/v3/snapshot.go
  pkg/discoveryservice/xdss/v3/snapshot_test.go
  pkg/envoy/config/v2/bootstrap.go
  pkg/envoy/equal.go
  pkg/envoy/equal_test.go
  pkg/envoy/resources/equal.go
  pkg/envoy/resources/equal_test.go
  pkg/envoy/resources/types.go
  pkg/envoy/resources/v2/secret.go
  pkg/envoy/resources/v2/secret_test.go
  pkg/envoy/resources/v2/type_urls.go
  pkg/envoy/resources/v3/type_urls.go
  pkg/envoy/serializer/v2/serializer.go
  pkg/envoy/serializer/v2/serializer_test.go
  pkg/envoy/types.go
  pkg/envoy/xds_server.go
  pkg/envoy/xds_server_test.go
  pkg/util/test/test.go
Labels: enhancement

#53 fix/secret-controller
  controllers/envoy/secrets_controller.go
  pkg/discoveryservice/manager.go
  test/e2e/04-certificates/00-assert.yaml
  test/e2e/04-certificates/00-install.yaml
  test/e2e/04-certificates/01-pod.yaml
  test/e2e/04-certificates/02-assert.yaml
  test/e2e/04-certificates/02-patch-envoyconfig.yaml
  test/e2e/04-certificates/03-validate-cert.yaml
  test/e2e/04-certificates/04-reissue-certificate.yaml
  test/e2e/04-certificates/05-validate-new-cert.yaml
  test/e2e/04-certificates/06-cleanup.yaml
Labels: bug

#55 Feat/Add ratelimit use case
  README.md
  docs/use-cases/ratelimit/README.md
  docs/use-cases/ratelimit/centos-pod.yaml
  docs/use-cases/ratelimit/kuard-deployment.yaml
  docs/use-cases/ratelimit/kuard-envoyconfig.yaml
  docs/use-cases/ratelimit/kuard-envoyproxy-sidecar-metrics-dashboard-screenshot.png
  docs/use-cases/ratelimit/kuard-podmonitor.yaml
  docs/use-cases/ratelimit/kuard-service.yaml
  docs/use-cases/ratelimit/limitador-config-configmap.yaml
  docs/use-cases/ratelimit/limitador-deployment.yaml
  docs/use-cases/ratelimit/limitador-grafanadashboard.json
  docs/use-cases/ratelimit/limitador-metrics-dashboard-screenshot.png
  docs/use-cases/ratelimit/limitador-podmonitor.yaml
  docs/use-cases/ratelimit/limitador-service.yaml
  docs/use-cases/ratelimit/ratelimit.svg
  docs/use-cases/ratelimit/redis-service.yaml
  docs/use-cases/ratelimit/redis-statefulset.yaml
Labels: documentation, enhancement

#56 feat/support-v3-envoy-resources
  .circleci/config.yml
  .gitignore
  Makefile
  apis/envoy/v1alpha1/envoyconfig_types.go
  apis/envoy/v1alpha1/envoyconfigrevision_types.go
  apis/envoy/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/envoy.marin3r.3scale.net_envoyconfigrevisions.yaml
  config/crd/bases/envoy.marin3r.3scale.net_envoyconfigs.yaml
  controllers/envoy/envoyconfig_controller.go
  controllers/envoy/envoyconfig_controller_test.go
  controllers/envoy/envoyconfigrevision_controller.go
  controllers/envoy/envoyconfigrevision_controller_test.go
  controllers/envoy/errors.go
  controllers/envoy/revisions.go
  controllers/envoy/revisions_test.go
  controllers/envoy/rollback.go
  controllers/envoy/suite_test.go
  controllers/operator/suite_test.go
  examples/e2e/pod/envoyconfig-v2.yaml
  examples/e2e/pod/envoyconfig-v3.yaml
  go.mod
  go.sum
  pkg/discoveryservice/manager.go
  pkg/discoveryservice/xds_server.go
  pkg/discoveryservice/xds_server_test.go
  pkg/discoveryservice/xdss/interface.go
  pkg/discoveryservice/xdss/v2/callbacks.go
  pkg/discoveryservice/xdss/v2/callbacks_test.go
  pkg/discoveryservice/xdss/v2/snapshot.go
  pkg/discoveryservice/xdss/v2/snapshot_test.go
  pkg/discoveryservice/xdss/v3/callbacks.go
  pkg/discoveryservice/xdss/v3/callbacks_test.go
  pkg/discoveryservice/xdss/v3/snapshot.go
  pkg/discoveryservice/xdss/v3/snapshot_test.go
  pkg/envoy/config/v2/bootstrap.go
  pkg/envoy/config/v2/bootstrap_test.go
  pkg/envoy/config/v3/bootstrap.go
  pkg/envoy/config/v3/bootstrap_test.go
  pkg/envoy/resources/generator.go
  pkg/envoy/resources/types.go
  pkg/envoy/resources/v2/resources.go
  pkg/envoy/resources/v2/resources_test.go
  pkg/envoy/resources/v2/secret.go
  pkg/envoy/resources/v2/type_urls.go
  pkg/envoy/resources/v2/type_urls_test.go
  pkg/envoy/resources/v3/resources.go
  pkg/envoy/resources/v3/resources_test.go
  pkg/envoy/resources/v3/type_urls.go
  pkg/envoy/resources/v3/type_urls_test.go
  pkg/envoy/serializer/serializer.go
  pkg/envoy/serializer/v2/serializer.go
  pkg/envoy/serializer/v2/serializer_test.go
  pkg/envoy/serializer/v3/serializer.go
  pkg/envoy/serializer/v3/serializer_test.go
  pkg/envoy/types.go
  pkg/reconcilers/envoy/cache.go
  pkg/reconcilers/envoy/cache_test.go
  pkg/util/test/test.go
Labels: enhancement
