Repository 3scale-sre/marin3r, pull requests merged in 2024-08, with the labels that each got.

#235 Remove konflux pipelines, in order to re-install
  .tekton/marin3r-pull-request.yaml
  .tekton/marin3r-push.yaml
Labels: lgtm, approved, size/L, needs-priority, needs-kind

#237 Bump to v0.13.1
  Makefile
  bundle/manifests/marin3r.clusterserviceversion.yaml
  catalog/marin3r/alpha-channel.yaml
  config/manager/kustomization.yaml
  config/webhook/kustomization.yaml
  pkg/image/zz_generated.go
  pkg/version/zz_generated.go
Labels: lgtm, approved, priority/important-soon, size/S, kind/release

#239 Add marin3r.v0.13.1 bundle to the index (II)
  catalog/marin3r/objects/marin3r.v0.13.1.clusterserviceversion.yaml
Labels: lgtm, approved, priority/important-soon, needs-size, kind/bug
