Repository 3scale-sre/marin3r, pull requests merged in 2025-05, with the labels that each got.

#269 fix/multi-platform
  Makefile
  api/operator.marin3r/v1alpha1/discoveryservice_types.go
  api/operator.marin3r/v1alpha1/zz_generated.deepcopy.go
  api/pkg/image/zz_generated.go
  api/pkg/version/zz_generated.go
  bundle/manifests/marin3r.clusterserviceversion.yaml
  bundle/manifests/operator.marin3r.3scale.net_discoveryservices.yaml
  catalog/marin3r/alpha-channel.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.1.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.11.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.2.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.3.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.4.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.5.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.6.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.7.clusterserviceversion.yaml
  catalog/marin3r/objects/marin3r.v0.13.2-alpha.8.clusterserviceversion.yaml
  config/crd/bases/operator.marin3r.3scale.net_discoveryservices.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/marin3r.clusterserviceversion.yaml
  config/test/kustomization.yaml
  config/test/manager_patch.yaml
  config/webhook/custom/deployment.yaml
  config/webhook/kustomization.yaml
  docs/development/README.md
  examples/k8s/envoydeployment/v0.11.1/envoydeployment.yaml
  examples/k8s/envoydeployment/v0.12.0/envoydeployment.yaml
  examples/k8s/envoydeployment/v0.12.0/kuard.yaml
  examples/k8s/oauth2/envoydeployment.yaml
  examples/k8s/olm/catalogsource.yaml
  examples/k8s/sidecars/discoveryservice.yaml
  examples/k8s/sidecars/kuard.yaml
  examples/quickstart/olm-install.yaml
  internal/controller/operator.marin3r/discoveryservice_controller.go
  internal/pkg/reconcilers/operator/discoveryservice/generators/deployment.go
  internal/pkg/reconcilers/operator/discoveryservice/generators/generator.go
  test/e2e/marin3r/suite_test.go
  test/e2e/util/generators.go
  vendor/github.com/3scale-sre/marin3r/api/operator.marin3r/v1alpha1/discoveryservice_types.go
  vendor/github.com/3scale-sre/marin3r/api/operator.marin3r/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale-sre/marin3r/api/pkg/image/zz_generated.go
  vendor/github.com/3scale-sre/marin3r/api/pkg/version/zz_generated.go
Labels: lgtm, approved, kind/feature, priority/important-longterm, size/L, kind/fix

#270 Fix refdocs generation
  Makefile
  docs/api-reference/config.yaml
  docs/api-reference/reference.asciidoc
Labels: lgtm, approved, priority/important-soon, size/XS, kind/fix

#271 fix: Update the repo name with the new org
  README.md
  hack/new-release.sh
Labels: lgtm, approved, priority/important-longterm, kind/cleanup, kind/documentation, size/S

#272 add go toolchain to go.mod
  api/go.mod
  go.mod
Labels: lgtm, approved, size/XS, needs-priority, needs-kind

#273 Apply some makefile fixes/improvements
  .github/workflows/catalog.yaml
  .github/workflows/go-lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  docs/api-reference/templates/asciidoctor/gv_details.tpl
  docs/api-reference/templates/asciidoctor/gv_list.tpl
  docs/api-reference/templates/asciidoctor/type.tpl
  docs/api-reference/templates/asciidoctor/type_members.tpl
Labels: lgtm, approved, kind/feature, priority/important-longterm, size/M, kind/cleanup, kind/fix

#276 Add v0.13.2 to catalog
  catalog/marin3r/alpha-channel.yaml
  catalog/marin3r/objects/marin3r.v0.13.2.clusterserviceversion.yaml
  catalog/marin3r/stable-channel.yaml
Labels: lgtm, approved, priority/important-soon, size/S, kind/release

#277 Fix catalog workflow
  .github/workflows/catalog.yaml
Labels: lgtm, approved, size/XS, needs-priority, needs-kind

#278 Automate api/ module tag in the release workflow
  .github/workflows/release.yaml
Labels: lgtm, approved, size/XS, needs-priority, kind/fix

#282 fix/keepalive-frequency
  Makefile
  examples/k8s/envoydeployment/v0.11.1/envoydeployment.yaml
  examples/k8s/envoydeployment/v0.12.0/discoveryservice.yaml
  examples/k8s/envoydeployment/v0.12.0/envoydeployment.yaml
  examples/k8s/oauth2/envoydeployment.yaml
  examples/k8s/sidecars/discoveryservice.yaml
  examples/k8s/sidecars/kuard.yaml
  examples/local/envoy-client-bootstrap.yaml
  examples/local/envoyconfig.yaml
  internal/pkg/discoveryservice/xds_server.go
  internal/pkg/envoy/bootstrap/v3/bootstrap.go
  internal/pkg/envoy/bootstrap/v3/bootstrap_test.go
  test/e2e/marin3r/discoveryservice_suite_test.go
  test/e2e/marin3r/envoydeployment_suite_test.go
  test/e2e/marin3r/pod_suite_test.go
  test/e2e/marin3r/sidecar_suite_test.go
  test/e2e/marin3r/suite_test.go
  test/e2e/util/generators.go
Labels: lgtm, approved, size/M, priority/important-soon, kind/fix

#284 Release v0.13.3
  Makefile
  api/pkg/image/zz_generated.go
  api/pkg/version/zz_generated.go
  bundle.Dockerfile
  bundle/manifests/marin3r.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/test/webhook_patch.yaml
  config/webhook/kustomization.yaml
  vendor/github.com/3scale-sre/marin3r/api/pkg/image/zz_generated.go
  vendor/github.com/3scale-sre/marin3r/api/pkg/version/zz_generated.go
Labels: lgtm, approved, priority/important-soon, size/S, kind/release

#285 Fix envvar name
  .github/workflows/release.yaml
Labels: lgtm, approved, priority/important-soon, size/XS, kind/fix
